apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: registry-1.docker.io/bitnamicharts
    chart: mongodb
    targetRevision: 15.6.16
    helm:
      values: |
        auth:
          enabled: false
        architecture: standalone
        persistence:
          enabled: true
          size: 2Gi
        image:
          registry: docker.io
          repository: bitnamilegacy/mongodb
          tag: 7.0.14-debian-12-r0
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: open5gs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
