apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open5gs-webui
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/cristyanmanta/gitops-open5gs-argocd.git
    targetRevision: main
    path: charts/open5gs-webui
    helm:
      values: |
        dbURI: "mongodb://open5gs-mongodb/open5gs"
        mongodb:
          enabled: false
          auth:
            enabled: false
        services:
          http:
            type: NodePort
            ports:
              http: 9999
            nodePorts:
              http: "30999"
        ingress:
          enabled: false
        resources:
          requests: { cpu: 50m, memory: 64Mi }
          limits: { cpu: 200m, memory: 128Mi }
  destination:
    server: https://kubernetes.default.svc
    namespace: open5gs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
